#!/usr/bin/env python3
"""Generate the /b/ bookmark redirect pages from b/bookmarks.json.

    T = title      t01, t02, ...
    B = bookmark   b1, b2, ...      (design, numbered per title)
    L = location   l00 = no fixed location, l01+ = a venue in the register

Printed on the bookmark:  https://prahran.press/b/t01/b1/l04
That address is permanent. Where it lands is whatever 'to' says in the config.

    python3 tools/build-bookmarks.py
    git add b && git commit -m "Update bookmark redirects" && git push
"""
import json
import pathlib
import html
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = ROOT / "b" / "bookmarks.json"
OUTDIR = ROOT / "b"
INTERNAL_HOST = "prahran.press"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting&hellip;</title>
<meta name="robots" content="noindex, nofollow">
<link rel="canonical" href="{dest_attr}">
<meta http-equiv="refresh" content="0; url={dest_attr}">
<script>location.replace("{dest_js}");</script>
<!-- {title_name} | {slug} | generated by tools/build-bookmarks.py -->
</head>
<body style="font-family:Georgia,serif;margin:0;padding:3rem 1.5rem;text-align:center;color:#222">
<p><a href="{dest_attr}">Continue to <em>{title_name}</em> &rarr;</a></p>
</body>
</html>
"""


def add_params(url, params):
    parts = urlsplit(url)
    q = dict(parse_qsl(parts.query, keep_blank_values=True))
    for k, v in params.items():
        q.setdefault(k, v)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(q), parts.fragment))


def destination(target, design, location, params, title_key):
    """Internal targets carry the design and location as query params so GA4
    records them. External targets (a bookshop) get UTM tags instead - their
    analytics will see those; ours will see nothing at all."""
    if urlsplit(target).netloc.lower().endswith(INTERNAL_HOST):
        return add_params(target, {params["design"]: design, params["location"]: location})
    return add_params(target, {
        "utm_source": "prahran-bookmark",
        "utm_medium": "qr",
        "utm_campaign": title_key,
        "utm_content": f"{design}-{location}",
    })


def main():
    cfg = json.loads(CONFIG.read_text())
    params = cfg["params"]
    locations = cfg.get("locations", {})
    rows = []

    for tkey, title in cfg["titles"].items():
        for batch, entry in title["batches"].items():
            design, location = batch.split("/")
            target = entry.get("to") or title["default"]
            dest = destination(target, design, location, params, tkey)
            slug = f"{tkey}/{design}/{location}"
            page = TEMPLATE.format(
                dest_attr=html.escape(dest, quote=True),
                dest_js=dest.replace("\\", "\\\\").replace('"', '\\"'),
                slug=slug,
                title_name=html.escape(title["name"]),
            )
            # written as a FILE, so /b/t01/b1/l00 answers with no trailing-slash hop
            out = OUTDIR / tkey / design / f"{location}.html"
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(page)
            rows.append((
                f"https://prahran.press/b/{slug}",
                title["name"],
                title["designs"].get(design, design),
                locations.get(location, location),
                dest,
            ))

    print(f"Wrote {len(rows)} redirect pages under /b/\n")
    for url, name, design, loc, dest in rows:
        print(f"  {url}")
        print(f"      {name} | {design} | {loc}")
        print(f"      -> {dest}\n")


if __name__ == "__main__":
    main()
