#!/usr/bin/env python3
"""Generate the /go/ bookmark redirect pages from go/redirects.json.

Usage:  python3 tools/build-go.py
Then:   git add go && git commit -m "Update bookmark redirects" && git push

Each printed QR code points at https://prahran.press/go/<slug>/ and never changes.
This script writes a tiny page at that address which bounces the visitor to
whatever 'to' says in the config. Change the config, re-run, push - the printed
bookmark keeps working and now lands somewhere new.
"""
import json
import pathlib
import html
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = ROOT / "go" / "redirects.json"
OUTDIR = ROOT / "go"
INTERNAL_HOST = "prahran.press"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting&hellip;</title>
<meta name="robots" content="noindex, nofollow">
<meta name="referrer" content="no-referrer-when-downgrade">
<link rel="canonical" href="{dest_attr}">
<meta http-equiv="refresh" content="0; url={dest_attr}">
<script>location.replace("{dest_js}");</script>
<!-- bookmark batch: {slug} | {note} | generated by tools/build-go.py -->
</head>
<body style="font-family:Georgia,serif;margin:0;padding:3rem 1.5rem;text-align:center;color:#222">
<p><a href="{dest_attr}">Continue to <em>The Art of Surrender</em> &rarr;</a></p>
</body>
</html>
"""


def add_params(url: str, params: dict) -> str:
    """Append query params without clobbering any already in the URL."""
    parts = urlsplit(url)
    existing = dict(parse_qsl(parts.query, keep_blank_values=True))
    for key, value in params.items():
        existing.setdefault(key, value)
    return urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(existing), parts.fragment)
    )


def destination(slug: str, target: str, ref_param: str) -> str:
    """Internal targets get ?ref=<slug> so GA4 on prahran.press records the scan.
    External targets (a bookshop) get UTM tags instead - that is all their
    analytics will accept, and our own GA4 cannot see the landing either way."""
    host = urlsplit(target).netloc.lower()
    if host.endswith(INTERNAL_HOST):
        return add_params(target, {ref_param: slug})
    return add_params(
        target,
        {
            "utm_source": "prahran-bookmark",
            "utm_medium": "qr",
            "utm_campaign": "art-of-surrender",
            "utm_content": slug,
        },
    )


def main() -> None:
    config = json.loads(CONFIG.read_text())
    default = config["default"]
    ref_param = config.get("ref_param", "ref")

    rows = []
    for slug, entry in config["batches"].items():
        target = entry.get("to") or default
        dest = destination(slug, target, ref_param)
        page = TEMPLATE.format(
            dest_attr=html.escape(dest, quote=True),
            dest_js=dest.replace("\\", "\\\\").replace('"', '\\"'),
            slug=slug,
            note=html.escape(entry.get("note", "")),
        )
        outfile = OUTDIR / slug / "index.html"
        outfile.parent.mkdir(parents=True, exist_ok=True)
        outfile.write_text(page)
        rows.append((slug, entry.get("note", ""), dest))

    width = max(len(r[0]) for r in rows)
    print(f"Wrote {len(rows)} redirect pages to /go/\n")
    for slug, note, dest in rows:
        print(f"  {slug.ljust(width)}  ->  {dest}")
        print(f"  {' '.ljust(width)}      {note}")


if __name__ == "__main__":
    main()
